version: "3.9"  # optional since v1.27.0
services:
  web:
    build: ./view
    ports:
      - "5000:5000"
    links:
      - redis
  redis:
    image: redis
  degradation:
    build: ./game
    environment:
      REDIS_HOST: redis
