version: "3.9"  # optional since v1.27.0
services:
  web:
    build: ./view
    ports:
      - "8080:8080"
    links:
      - redis
    environment:
      PORT: 8080
      REDIS_HOST: redis
      REDIS_PORT: 6379
  redis:
    image: redis
    ports:
      - "6379:6379"
