version: "3.9"  # optional since v1.27.0
services:
  web:
    build: ./view
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      REDIS_HOST: redis
      REDIS_PORT: 6379
    links:
      - redis
  redis:
    image: redis
  degradation:
    build: ./game
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379

      CONSOLE_LOG_LEVEL: DEBUG
      FILE_LOG_LEVEL: DEBUG
